### ISSUE TITLE
I cannot install properly Circular on Digital Ocean VPS

### ISSUE THREAD

**Issue by kostGX** [julien-c/Circular#43]
Hey,

I love very much what @julien-c has created and I would like to install it on my own VPS.
I went step by step the installation README file, searching and executing guides and tutorials to get my prerequisites straight. I am now blocked at the point where I am supposed to run

php Daemon/run.php

But it seems to give me this error:

PHP Warning:  require(/var/www/html/buffer/Daemon/../extlib/tmhOAuth/tmhOAuth.php): failed to open stream: No such file or directory in /var/www/html/buffer/Daemon/ParallelTasks.php on line 5
PHP Fatal error:  require(): Failed opening required '/var/www/html/buffer/Daemon/../extlib/tmhOAuth/tmhOAuth.php' (include_path='/var/www/html/buffer/Daemon:/var/www/html/buffer:/var/www/html/buffer/extlib/PHP-Daemon::.:/usr/share/php:/usr/share/pear') in /var/www/html/buffer/Daemon/ParallelTasks.php on line 5

I searched around for this but I couldn't get to any solid/working solutions.

If someone could helped me out with this, it would be great and I would be really grateful and thankful.

Thanks in advance,

Kostas

**Comment by julien-c** [comment]
You probably haven't cloned the repo's submodules: 
```
git submodule update --init --recursive
```

Cf. http://stackoverflow.com/questions/3796927/how-to-git-clone-including-submodules

**Comment by kostGX** [comment]
Thank you very much. That helped. I am closing this issue (only to open a new one on a different thing -_-)
