### ISSUE TITLE
Error 405 (Method Not Allowed)

### ISSUE THREAD

**Issue by kostGX** [julien-c/Circular#44]
Hey again!

I managed to run Circular and sign in with Twitter. Now I have trouble making posts. All in-app actions I make return an Error 405, method not allowed from Twitter. The links that "go off" are

api/settings
api/times and
api/posts

I am using nginx.

Thank you in advance.

PS In which folder am I supposed to create the 'uploads' folder?

Update: I tried placing this 

To allow POST on static pages
    error_page  405     =200 $uri;

In my configuration. I wouldn't receive any errors on the console but it still wouldn't post.

**Comment by julien-c** [comment]
`v2` is going to be a complete backend rewrite using a different stack (Node), so closing this issue. Cheers!
