### ISSUE TITLE
Remove accounts from DB?

### ISSUE THREAD

**Issue by kostGX** [julien-c/Circular#45]
How can I remove accounts from the DB? I am getting an invalid OAuth response after revoking and re-authorizing access from one of the accounts. :-/

`"{\"errors\":[{\"message\":\"Invalid or expired token\",\"code\":89}]}"{"id":"54ad4ffdf0c2981c5f000001","users":{"54ad4ffdf0c2981c5f000000":{"user_id":2966104913,"user_screen_name":"PhotosSailing","profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/552839685047717888\/9nuXADG2_normal.jpeg","name":"Sailing","id":"54ad4ffdf0c2981c5f000000"},"54ad5078f0c298945e000000":[],"54ad50c8f0c2981c5f000002":{"user_id":2937010654,"user_screen_name":"startupurdreams","profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/547041795419287552\/fL6tb_KU_normal.png","name":"Tech Startups","id":"54ad50c8f0c2981c5f000002"},"54ad5203f0c298d95f000000":{"user_id":2965880583,"user_screen_name":"streetartworks_","profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/552806845606154242\/NOp4x72e_normal.jpeg","name":"Street Art","id":"54ad5203f0c298d95f000000"},"54ad52d2f0c298d95f000001":{"user_id":2385077040,"user_screen_name":"ItsPuppyWorld","profile_image_url":"http:\/\/pbs.twimg.com\/profile_images\/545177764324593664\/_VWv8gZ7_normal.jpeg","name":"Puppies","id":"54ad52d2f0c298d95f000001"}}}`

Thank you!

**Comment by julien-c** [comment]
@kostGX Do you still have issues on this? I will take a look soon.

**Comment by kostGX** [comment]
Yes I do. Thanks a lot for getting back to me! Let me know of how I can be of help!






—

**Comment by julien-c** [comment]
Konstantinos, I will look into it this afternoon (European time), so if you're around please let me know if you can help test the app. Thanks!

**Comment by kostGX** [comment]
Sure! I am on GMT +2 and I will be available. The damage happened when I connected by mistake another account and when I removed access to Circular they all failed to work! 




See you in the afternoon!



—

**Comment by kostGX** [comment]
@julien-c Goodmorning and have a great week! Hope all is good! 
I will be online most of the time this week FYI.

**Comment by csu** [comment]
@julien-c I'm having this same problem.

`GET http://circular.io/api/oauth.php 500 (Internal Server Error)`

`errors":[{"code":89,"message":"Invalid or expired token."}]}...`
