### ISSUE TITLE
Circular gets stuck on the loading spinner

### ISSUE THREAD

**Issue by csu** [julien-c/Circular#46]
When I try to use circular.io, I get stuck on the loading spinner:

![problem](https://cloud.githubusercontent.com/assets/164822/6113405/ef89acc0-b04b-11e4-9f7c-909c3f2a728b.gif)

For reference, my Twitter is: [@nitrogen](http://twitter.com/nitrogen)

**Comment by csu** [comment]
I'm still having this problem. I think it's related to #9. I'm getting the same error: `GET http://circular.io/api/oauth.php 500 (Internal Server Error)`.

cc @julien-c

**Comment by julien-c** [comment]
Closing this issue in favor of #38
