### ISSUE TITLE
Twitter character counter should account for Twitter automatic link shortening.

### ISSUE THREAD

**Issue by dhilowitz** [julien-c/Circular#48]
There's an easy way to implement this as Twitter offer a javascript library for counting characters: https://github.com/twitter/twitter-text/tree/master/js

*Remaining character count example&

    var tweet = "This is a test tweet":
    var remainingCharacters = 140 - twttr.txt.getTweetLength(tweet);

getTweetLength returns the computed length of a tweet after taking into consideration t.co URL shortening and non UTF-16 characters

**Comment by julien-c** [comment]
Good idea. Care to try and have a shot at implementing it?

Otherwise I'll try and do it.

**Comment by potomak** [comment]
I'd like to work on this feature if help is needed.

**Comment by dhilowitz** [comment]
Go for it! I probably won't have any free time for a month or two. :(

**Comment by julien-c** [comment]
Closed by #58. Hat tip @potomak :)

**Comment by potomak** [comment]
@julien-c I think this could be closed now, my update seems to work.
