### ISSUE TITLE
My Circular is unable to pull from Mongo. See screenshot of error.

### ISSUE THREAD

**Issue by dhilowitz** [julien-c/Circular#49]
I set Circular up _exactly_ the way the readme described. Unfortunately, I'm getting this error when I get to the main dashboard.

![screen shot 2015-02-28 at 1 27 08 pm](https://cloud.githubusercontent.com/assets/581406/6427411/8d23de0a-bf4d-11e4-955e-f67371495182.png)

I looked in Mongo, and it looks like collections are being created.

**Comment by dhilowitz** [comment]
The issue is related to this: https://jira.mongodb.org/browse/PHP-1051

We just need to surround `$app['account']['users']` with array_values():

    $m->circular->posts->remove(array(
		'_id'      => new MongoId($id),
		'user._id' => array('$in' => array_values($app['account']['users']))
	));

**Comment by julien-c** [comment]
@dhilowitz Do you mind opening a Pull request?

**Comment by dhilowitz** [comment]
I've created a pull request. (It's issue #59)
