### ISSUE TITLE
Thought I'd do the honor of warning you that you have an open directory on your server

### ISSUE THREAD

**Issue by pinilpypinilpy** [julien-c/Circular#76]
http://buffalo.circular.io/
Full of NSFW stuff
Didn't know how else to tell you
You might want to make that private :/

**Comment by Reeceeboii** [comment]
If we don't get a response soon, might be worth directly contacting the repo owner via email or Twitter, just to make sure he's aware :)

**Comment by julien-c** [comment]
Thanks for the report. Should be fixed now.
